<?php
   // Exit if accessed directly.
   if ( ! defined( 'ABSPATH' ) ) {
      exit;
   }

   class FlipForBusiness_Gateway extends FlipForBusiness_Abstract {
      /**
       * Constructor
       */
      function __construct() {
         $this->id = "flip";
         $this->method_title = $this->pluginTitle();
         $this->method_description = $this->getSettingsDescription();
         $this->has_fields   = true;
         
         parent::__construct();
         add_action( 'woocommerce_update_options_payment_gateways_' . $this->id, array( &$this, 'process_admin_options'));
         add_action( 'woocommerce_receipt_' . $this->id, array($this, 'receipt_page'));
      }

      /**
       * Admin Panel Options
       * See definition on the extended abstract class
       * @access public
       * @return void
       */
      public function admin_options() { ?>
         <h3><?php echo esc_html($this->pluginTitle()); ?></h3>
         <p><?php echo esc_html($this->getSettingsDescription()); ?></p>
         <table class="form-table">
            <?php
               // Generate the HTML For the settings form. generated from `init_form_fields`
               echo esc_html($this->generate_settings_html());
            ?>
         </table>
         <?php
      }

      /**
       * Handle of get_supports
       * @return array
       */
      public function get_supports() {
         return $this->supports;
      }

      /**
       * Hook function that will be auto-called by WC on customer initiate payment
       * act as entry point when payment process is initated
       * @param  string $order_id generated from WC
       * @return array contains redirect_url of payment for customer
       */
      public function process_payment( $order_id ) {
         global $woocommerce;
         // pass through the real function handling the logic
         return $this->process_payment_helper($order_id);
      }

      /**
       * Helper function to handle additional params from sub separated gateway buttons 
       * @param  string $order_id auto generated by WC
       * @param  array mixed array opts, used by sub separated gateway buttons classes
       * @return array contains redirect_url of payment for customer
       */
      public function process_payment_helper($order_id, $options = false) {
         global $woocommerce;
         $order = new WC_Order( $order_id );
         // Get response object template
         $successResponse = $this->getResponseTemplate( $order );
         
         // Get data for charge to API
         $params = $this->getPaymentRequestData( $order_id );

         if (
            !empty($order->get_meta('_flip_link_id')) && 
            !empty($order->get_meta('_flip_expired_date')) && 
            !FlipForBusiness_Utils::flip_is_expired($order->get_meta('_flip_expired_date')) 
         ) {
            $redirectUrl = $order->get_meta('_flip_link_url');
         } else {
            try {
               $result_accept_payment = FlipForBusiness_Api::createBillTransaction( $order, $params );

               if (!empty($result_accept_payment->link_id)) {
                  $order->update_meta_data('_flip_link_id', $result_accept_payment->link_id);
                  $order->update_meta_data('_flip_link_url', $result_accept_payment->link_url);
                  $order->update_meta_data('_flip_expired_date', $result_accept_payment->expired_date);
                  
                  // Ensure the redirect URL is absolute by prepending 'https://' if necessary
                  $redirectUrl = (strpos($result_accept_payment->link_url, 'http') === 0) ? $result_accept_payment->link_url : 'https://' . $result_accept_payment->link_url;
               }
            } catch (\Exception $e) {
               $this->setLogError($e->getMessage());
               throw new Exception(esc_html($e->getMessage()));
            }
         }
         
         $order->save();

         // Empty the cart because payment is initiated.
         $woocommerce->cart->empty_cart();

         // set wc order's finish_url on user's session cookie
         $this->set_finish_url_user_cookies($order);

         $successResponse['redirect'] = $redirectUrl;
         return $successResponse;
      }

      /**
       * Hook function that will be called on receipt page
       * Output HTML for Iframe payment page.
       * @param  string $order_id generated by WC
       * @return string HTML
       */
      public function receipt_page( $order_id ) {
         global $woocommerce;
         $pluginName = 'fullpayment';

         require_once(dirname(__FILE__) . '/payment-page.php'); 
      }

      /**
       * @return string
       */
      public function pluginTitle() {
         return "Flip for Business";
      }

      /**
       * @return string
       */
      protected function getSettingsDescription() {
         return __("Flip for Business is a robust plugin that integrates Flip's secure and efficient payment processing directly into your WordPress e-commerce site. With this plugin, you can offer your customers a smooth, reliable payment experience without ever leaving your store.", 'flip-for-business');
      }
   }