<?php
   // Exit if accessed directly.
   if ( ! defined( 'ABSPATH' ) ) {
      exit;
   }

   abstract class FlipForBusiness_Abstract extends WC_Payment_Gateway {
      /**
       * Unique id for the gateway.
       * @var string
       *
       */
      public $id = 'flip';

      /**
       * Constructor for the FlipForBusiness_Abstract.
       */
      public function __construct() {
         $this->icon = ''; // URL of the icon that will be displayed in the checkout page
         $this->has_fields = true;
         $this->supports = array(
            'pre-orders',
            'products',
            'blocks',
            // 'refunds'
         );
         
         // Load the settings.
         $this->init_form_fields();
         $this->init_settings();

         // Define user set variables.
         $this->title = $this->get_option('title');
         $this->description = $this->get_option('description');
         $this->instructions = $this->get_option('instructions');
         $this->environment = $this->get_option('environment');
         $this->api_key_sandbox = $this->get_option('api_key_sandbox');
         $this->api_key_production = $this->get_option('api_key_production');
         $this->token_validation_sandbox = $this->get_option('token_validation_sandbox');
         $this->token_validation_production = $this->get_option('token_validation_production');
         $this->order_id_prefix = $this->get_option('order_id_prefix');
         $this->expiry = $this->get_option('expiry');

         // Actions.
         add_action( 'woocommerce_update_options_payment_gateways_' . $this->id, array( &$this, 'process_admin_options' ) );
         // Hook for adding custom HTML on thank you page (for payement/instruction url)
         add_action( 'woocommerce_thankyou_'. $this->id, array( $this, 'view_order_and_thankyou_page' ) );
         // Hook for adding custom HTML on view order menu page My Account
         add_action( 'woocommerce_order_details_after_order_table', array( $this, 'view_order_and_thankyou_page' ) );

         if($this->id == 'flip') {
            // init notif handler class, which also add action hook to handle notif
            $notifHandler = new FlipForBusiness_Notify_Handler();
         }
      }

      /**
       * Register Form Field Admin Settings
       */
      public function init_form_fields() {
         $this->form_fields = require( dirname(__FILE__) . '/../flip-admin-settings.php');
      }
      
      /**
       * Hook function that will be auto-called by WC on thank you page
       * Output HTML for payment/instruction URL
       * @param  string $order_id generated by WC
       * @return string HTML
       */
      public function view_order_and_thankyou_page( $order_id ) {
         require_once( dirname(__FILE__) . '/../order-view-and-thankyou-page.php');
      }

      /**
       * Summary of process_refund
       * @param mixed $order_id
       * @param mixed $amount
       * @param mixed $reason
       * @return mixed
       */
      public function process_refund($order_id, $amount = null, $reason = '') {
         $order = wc_get_order( $order_id );
         $bank_code = $order->get_meta('_flip_account_refund_bank', true);
         $account_number = $order->get_meta('_flip_account_refund_number', true);
         $flip_refund_transaction_id = $order->get_meta('_flip_refund_transaction_id', true);
         $email = FlipForBusiness_Utils::getOrderProperty($order,'billing_email');

         if (empty($bank_code)) {
            return new WP_Error( 'flip_refund_error', 'Bank/e-Wallet missing');
         }

         if (empty($account_number)) {
            return new WP_Error( 'flip_refund_error', 'Account Number missing');
         }

         if (empty($email)) {
            return new WP_Error( 'flip_refund_error', 'Email missing');
         }
         
         if ($amount < 10000) {
            return new WP_Error( 'flip_refund_error', 'Amount refund missing');
         }

         if (!empty($flip_refund_transaction_id)) {
            return new WP_Error( 'flip_refund_error', "Can't request a refund again as one has already been processed for this transaction.");
         }

         try {
            $refundResponse = $this->refund( $order_id, $bank_code, $account_number, $amount, $reason, $email );
         } catch (Exception $e) {
            $this->setLogError( $e->getMessage() );
            return new WP_Error( 'flip_refund_error', $e->getMessage());
         }

         if (!empty($refundResponse->id)) {
            $order->update_meta_data('_flip_refund_transaction_id', $refundResponse->id );
            /* translators: 1: Refund transaction status, 2: Bank used for the refund */
            $order->update_status('on-hold', sprintf(__('Refund payment Transaction %1$s. Bank %2$s', 'flip-for-business'), $refundResponse->status, $refundResponse->sender_bank));
            /* translators: 1: Refund amount, 2: Refund ID, 3: Refund reason */
            $order->add_order_note(sprintf(__('Refunded %1$s - Refund ID: %2$s - Reason: %3$s', 'flip-for-business'), wc_price($refundResponse->amount), $refundResponse->id, $reason));
            
            $order->save();

            return $refundResponse->id;
         }
      }

      /**
       * Summary of refund
       * @param int $oder_id
       * @param mixed $bank_code
       * @param mixed $account_number
       * @param mixed $amount
       * @param mixed $reason
       * @param mixed $email
       * @return Throwable|Exception|object|string
       */
      public function refund($order_id, $bank_code, $account_number, $amount, $reason, $email) {
         try {
            $body = array(
               'account_number' => $account_number,
               'bank_code' => $bank_code,
               'amount' => (float)$amount,
               'beneficiary_email' => $email
            );
   
            if (!empty($reason)) {
               $body['remark'] = $reason;
            }

            $response = FlipForBusiness_Api::createRefund($body, $order_id);
         } catch (\Throwable $e) {
            throw $e;
         }

         return $response;
      }

      public function receipt_page( $order_id ) {
         global $woocommerce;
         $pluginName = 'fullpayment';
         
         // Separated as Shared PHP included by multiple class
         require_once(dirname(__FILE__) . '/payment-page.php');
      }

      public function getResponseTemplate( $order ) {
         // Response object template
         $successResponse = array(
            'result'  => 'success',
            'redirect' => ''
         );

         // If flip link url exists on the current $Order, reuse it
         // Prevent duplication of API call, which may throw API error
         if (FlipForBusiness_Utils::has_flip_link_url($order)){
            $successResponse['redirect'] = FlipForBusiness_Utils::get_flip_link_url($order, true);
         }

         return $successResponse;
      }

      /**
       * Plugin config and cart/order properties are used as params
       * Custom helper function to generate Flip API params/payload
       * @param $order_id
       * @return object|array $params
       */
      public function getPaymentRequestData( $order_id ) {
         $order = new WC_Order( $order_id );
         
         $params = array(
            'transaction_details' => array(
               'order_id' => $order_id,
               'gross_amount' => 0,
            )
         );

         $nonce = wp_create_nonce('woocommerce-order_' . $order_id);

         $customer_details = array();
         $customer_details['first_name'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_first_name');
         $customer_details['first_name'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_first_name');
         $customer_details['last_name'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_last_name');
         $customer_details['email'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_email');
         $customer_details['phone'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_phone');
         $customer_details['address'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_address_1');

         $billing_address = array();
         $billing_address['first_name'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_first_name');
         $billing_address['last_name'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_last_name');
         $billing_address['address'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_address_1');
         $billing_address['city'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_city');
         $billing_address['postal_code'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_postcode');
         $billing_address['phone'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_phone');
         $converted_country_code = FlipForBusiness_Utils::getOrderProperty($order, 'billing_country');
         $billing_address['country_code'] = (strlen($converted_country_code) != 3 ) ? 'IDN' : $converted_country_code ;

         $customer_details['billing_address'] = $billing_address;
         $customer_details['shipping_address'] = $billing_address;

         if ( isset ( $_POST['ship_to_different_address'] ) && wp_verify_nonce($nonce, 'flip-for-business')) {
            $shipping_address = array();

            $shipping_address['first_name'] = FlipForBusiness_Utils::getOrderProperty($order,'shipping_first_name');
            $shipping_address['last_name'] = FlipForBusiness_Utils::getOrderProperty($order,'shipping_last_name');
            $shipping_address['address'] = FlipForBusiness_Utils::getOrderProperty($order,'shipping_address_1');
            $shipping_address['city'] = FlipForBusiness_Utils::getOrderProperty($order,'shipping_city');
            $shipping_address['postal_code'] = FlipForBusiness_Utils::getOrderProperty($order,'shipping_postcode');
            $shipping_address['phone'] = FlipForBusiness_Utils::getOrderProperty($order,'billing_phone');
            $converted_country_code = FlipForBusiness_Utils::getOrderProperty($order,'shipping_country');
            $shipping_address['country_code'] = (strlen($converted_country_code) != 3 ) ? 'IDN' : $converted_country_code;
            $customer_details['shipping_address'] = $shipping_address;
         }
         
         $params['customer_details'] = $customer_details;

         $params['transaction_details']['gross_amount'] = FlipForBusiness_Utils::getOrderProperty($order, 'total');
         $params['redirect_payment_url'] = FlipForBusiness_Utils::getOrderProperty($order, 'checkout_payment_url');
         $params['redirect_url'] = FlipForBusiness_Utils::getOrderProperty($order, 'checkout_payment_url');
         $params['redirect_thankyou_url'] =  FlipForBusiness_Utils::getOrderProperty($order, 'checkout_order_received_url');
         
         // add `expiry` API params
         $params['expiry'] = !empty($this->expiry) ? FlipForBusiness_Utils::calculateTime($this->expiry) : FlipForBusiness_Utils::calculateTime("30 minutes");

         return $params;
      }

      /**
       * Custom helper function to set customer web session cookies of WC order's finish_url
       * That will be used by finish url handler to redirect customer to upon finish url is reached
       * Cookies is used to strictly allow only the transacting-customer 
       * to access the order's finish url
       * @TAG: finish_url_user_cookies
       * @param WC_Order $order WC Order instance of the current transaction
       */
      public function set_finish_url_user_cookies($order) {
         $cookie_name = 'wc_flip_last_order_finish_url';
         $order_finish_url = $order->get_checkout_order_received_url();
         setcookie($cookie_name, $order_finish_url);
      }

      /**
       * Summary of setLogError
       * @param mixed $message
       * @return void
       */
      public function setLogError($message) {
         FlipForBusiness_Logger::log($message, 'flip-error', $this->id, current_time('timestamp'));
      }

      /**
       * @return string The main gateway plugin's Notification URL that will be displayed to config page
       *
      */
      public function get_main_notification_url() {
         return add_query_arg( 'wc-api', 'FlipForBusiness_Gateway', home_url( '/' ) );
      }

      /**
       * Process admin options and sanitize the order_id_prefix field
       */
      public function process_admin_options() {
         // Get all settings before sanitizing
         $all_settings = $this->get_post_data();
         
         // Sanitize order_id_prefix to only allow alphanumeric characters, hyphens, and underscores
         if (isset($all_settings['woocommerce_' . $this->id . '_order_id_prefix'])) {
            $prefix = $all_settings['woocommerce_' . $this->id . '_order_id_prefix'];
            $sanitized_prefix = preg_replace('/[^a-zA-Z0-9_\-]/', '', $prefix);
            
            // If empty after sanitizing, set to default
            if (empty($sanitized_prefix)) {
               $sanitized_prefix = 'FWOrder-';
            }
            
            // Update the value in the post data
            $_POST['woocommerce_' . $this->id . '_order_id_prefix'] = $sanitized_prefix;
         }
         
         // Call parent method to save settings
         return parent::process_admin_options();
      }
   }